[tool.poetry]
name = "psse34parser"
version = "0.0.2"
description = ""
authors = ["jbarberia <jbarberia@frba.utn.edu.ar>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1"
pandas = "1.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
